Clarifying changes to OSX install instructions
muralikbk/cloud-computing-tutorial pull request #2
Opened 2020-11-04 07:02 UTC by kinjalp516

2020-11-04 07:11 UTC, muralikbk requested changes
See comments.
Also, keep branch name specific to the changes - adding the name is optional. e.g. name could be kinjal_osx_install_instruction_update.
Create new branches for each set of changes.

2020-11-04 07:11 UTC, muralikbk commented on Install-instructions/Install-instructions-for-OSX.md
> +cat ~/.ssh/[KEY_FILE_NAME] >> ~/.ssh/authorized_keys
id_rsa.pub is the default key file - if we are using a different file name, multiple commands and settings will need to change including the ssh-keygen command. Did you get all of them?

2020-11-04 07:11 UTC, muralikbk commented on Install-instructions/Install-instructions-for-OSX.md
> +alias hstart="//usr/local/Cellar/hadoop/3.3.0/sbin/sbin/start-dfs.sh;//usr/local/Cellar/hadoop/3.3.0/sbin/sbin/start-yarn.sh"
If you are changing hadoop_dir to [HADOOP_PATH] change in all the locations. Also, there are two // at the beginning of the path, making it non accessable.

2020-11-04 07:13 UTC, kinjalp516 commented on Install-instructions/Install-instructions-for-OSX.md
> +cat ~/.ssh/[KEY_FILE_NAME] >> ~/.ssh/authorized_keys
I just had to input the file name when I was doing it, and then changed it there. It asked me to specify one, so should we write that they should instead name it that?

2020-11-04 07:13 UTC, kinjalp516 commented on Install-instructions/Install-instructions-for-OSX.md
> +alias hstart="//usr/local/Cellar/hadoop/3.3.0/sbin/sbin/start-dfs.sh;//usr/local/Cellar/hadoop/3.3.0/sbin/sbin/start-yarn.sh"
Yes, will change that - my mistake. Also, will do

2020-11-04 07:17 UTC, muralikbk commented on Install-instructions/Install-instructions-for-OSX.md
> +cat ~/.ssh/[KEY_FILE_NAME] >> ~/.ssh/authorized_keys
It isn't a bad idea to have a custom key file name. But it will need to be changed in too many places, so I stuck with the default.
If you can find all the locations the file needs to be changed, then we can have the differently named file.
If not, keep it as default for now and I'll add it to the TODO list

2020-11-05 13:18 UTC, muralikbk approved these changes
Approved.

2020-11-05 13:19 UTC, merged